services:
  ldap:
    build: ./ldap
    container_name: ldap_chorizo
    env_file:
      - .env
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}
      - LDAP_READONLY_USER=${LDAP_READONLY_USER}
      - LDAP_READONLY_USER_USERNAME=${LDAP_READONLY_USER_USERNAME:-readonly}
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD:-readonly-pass}
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./volumes/ldap-data:/var/lib/ldap
    restart: unless-stopped
    networks:
      - ldapnet


  # phpldapadmin:
  #   image: osixia/phpldapadmin:0.9.0
  #   container_name: phpldapadmin
  #   environment:
  #     - PHPLDAPADMIN_LDAP_HOSTS=${PHPLDAPADMIN_LDAP_HOSTS}
  #     - PHPLDAPADMIN_HTTPS=${PHPLDAPADMIN_HTTPS}
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - ldap
  #   restart: unless-stopped
  #   networks:
  #     - ldapnet

  apache:
    build:
      context: ./apache
    container_name: apache_ssl
    ports:
      # - "8080:80"
      - "443:443"
    volumes:
      - ./volumes/apache-html:/var/www/html
      - ./volumes/apache-settins:/var/www/
    depends_on:
      - ldap
    restart: always
    networks:
      - ldapnet

networks:
  ldapnet:
    driver: bridge
